# -*- coding: utf-8 -*-
"""Gradio UI test 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AnUAH3rqw4bJz4ttUF8hPatKZuamuzQy
"""

import gradio as gr
import time

def load_transcription_to_list(filepath):
    transcription_inputs = []
    encodings = ['utf-8', 'latin-1', 'cp1252']

    for encoding in encodings:
        try:
            with open(filepath, 'r', encoding=encoding) as file:
                for line in file:
                    line_text = line.strip()
                    if line_text:
                        transcription_inputs.append(line_text)
            return transcription_inputs
        except UnicodeDecodeError:
            continue
        except FileNotFoundError:
            return [f"Error: Could not find '{filepath}'."]

    return ["Error: Could not decode file."]

def process_audio(audio_filepath):
    """
    This function is triggered when the user clicks the process button.
    'audio_filepath' is the temporary file Gradio creates from the microphone recording.
    """
    if not audio_filepath:
        return "Please record some audio first!"

    # In your real pipeline, you would pass `audio_filepath` to your STT model here.
    # For now, we'll simulate the STT model taking a second to process...
    time.sleep(1)

    txt_output_path = "ejemplo.txt"

    text_lines = load_transcription_to_list(txt_output_path)
    display_text = "\n".join(text_lines)
    # TO-DO, pasar el texto al modelo aqui
    return display_text

# UI
with gr.Blocks(theme=gr.themes.Soft()) as demo:
    gr.Markdown("# Speech to Text, SVM UI")
    gr.Markdown("Click the microphone to record. Once finished, click **Process Audio** to read the generated `.txt` file.")

    with gr.Row():
        with gr.Column():
            audio_in = gr.Audio(sources=["microphone"], type="filepath", label="Record Audio")
            submit_btn = gr.Button("Process Audio", variant="primary")

        with gr.Column():
            text_out = gr.Textbox(label="Transcription Output", lines=15, interactive=False)

    # Button to function
    submit_btn.click(
        fn=process_audio,
        inputs=audio_in,
        outputs=text_out
    )

if __name__ == "__main__":
    demo.launch()

"""### VER 2"""

import gradio as gr
import time

# 1. Our resilient loading function
def load_transcription_to_list(filepath):
    transcription_inputs = []
    encodings = ['utf-8', 'latin-1', 'cp1252']

    for encoding in encodings:
        try:
            with open(filepath, 'r', encoding=encoding) as file:
                for line in file:
                    line_text = line.strip()
                    if line_text:
                        transcription_inputs.append(line_text)
            return transcription_inputs
        except UnicodeDecodeError:
            continue
        except FileNotFoundError:
            return [f"Error: Could not find '{filepath}'."]

    return ["Error: Could not decode file."]

# 2. UI State Management Functions
def start_call_ui():
    """Updates the buttons to show the call is active."""
    return gr.update(interactive=False, value="Call in Progress..."), gr.update(interactive=True)

def end_call_ui():
    """Resets the buttons when the call ends."""
    return gr.update(interactive=True, value="Take Call"), gr.update(interactive=False)

def monitor_transcription():
    """
    This function runs continuously while the call is active.
    It yields new data to the UI every 2 seconds.
    """
    txt_output_path = "ejemplo.txt"

    while True:
        # Load the latest text from the file
        text_lines = load_transcription_to_list(txt_output_path)
        display_text = "\n".join(text_lines)

        # (Future step: Pass 'text_lines' to your SVM model here to get predictions)
        # (e.g., append a stress warning to the display_text if detected)

        # 'yield' pushes the update to the Gradio UI without stopping the function
        yield display_text

        # Wait 2 seconds before checking the file again
        time.sleep(2)

with gr.Blocks(theme=gr.themes.Soft()) as demo:
    gr.Markdown("# Live Agent Stress Assessment")
    gr.Markdown("Click **Take Call** to start monitoring the live transcription.")

    with gr.Row():
        with gr.Column(scale=1):
            take_call_btn = gr.Button("Take Call", variant="primary")
            end_call_btn = gr.Button("End Call", variant="stop", interactive=False)

        with gr.Column(scale=2):
            # The text box to display the continuously updating contents
            text_out = gr.Textbox(label="Live Transcription Output", lines=15, interactive=False)

    # --- The Wiring ---

    # 1. When "Take Call" is clicked, update the buttons...
    start_event = take_call_btn.click(
        fn=start_call_ui,
        outputs=[take_call_btn, end_call_btn]
    ).then(
        # ...and immediately start the continuous monitoring loop.
        fn=monitor_transcription,
        outputs=text_out
    )

    end_call_btn.click(
        fn=end_call_ui,
        outputs=[take_call_btn, end_call_btn],
        # ...and CANCEL the monitoring loop so it stops running in the background.
        cancels=[start_event]
    )

if __name__ == "__main__":
    demo.launch()